include:
  - board: xiao_ble
    shield: Fern_left
  - board: xiao_ble
    shield: Fern_right
  - board: xiao_ble
    shield: DONGLE_DISPLAY_091_OLED
  - board: xiao_ble
    shield: settings_reset

