include:
  - board: xiao_ble
    shield: Fern_left
  - board: xiao_ble
    shield: Fern_right
  - board: xiao_ble
    shield: Fern_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: settings_reset
